SUBTITLE_PRESETS = {
    "MrBeast Clean Hook": {
        "font_name": "Montserrat-ExtraBold",
        "font_size": 32,
        "base_color": "#FFFFFF",
        "highlight_color": "#FFD700",
        "outline_color": "#000000",
        "outline_thickness": 3,
        "shadow_color": "#000000",
        "shadow_size": 2,
        "bold": True,
        "italic": False,
        "uppercase": True,
        "highlight_size": 38,
        "words_per_block": 3,
        "gap_limit": 0.25,
        "mode": "highlight",
        "underline": False,
        "strikeout": False,
        "border_style": 1,
        "vertical_position": 180,
        "alignment": 2,
        "remove_punctuation": True,
    },
    "Hormozi (Classic)": {
        "font_name": "Montserrat-ExtraBold",
        "font_size": 30,
        "base_color": "#FFFFFF",
        "highlight_color": "#00FF00",
        "outline_color": "#000000",
        "outline_thickness": 3,
        "shadow_color": "#000000",
        "shadow_size": 0,
        "bold": True,
        "italic": False,
        "uppercase": True,
        "highlight_size": 35,
        "words_per_block": 2,
        "gap_limit": 0.5,
        "mode": "highlight",
        "underline": False,
        "strikeout": False,
        "border_style": 1,
        "vertical_position": 200,
        "alignment": 2,
        "remove_punctuation": True,
    },
    "Beasty (Loud)": {
        "font_name": "Arial",
        "font_size": 34,
        "base_color": "#FFFFFF",
        "highlight_color": "#FF0000",
        "outline_color": "#000000",
        "outline_thickness": 3,
        "shadow_color": "#000000",
        "shadow_size": 3,
        "bold": True,
        "italic": False,
        "uppercase": True,
        "highlight_size": 40,
        "words_per_block": 3,
        "gap_limit": 0.4,
        "mode": "highlight",
        "underline": False,
        "strikeout": False,
        "border_style": 1,
        "vertical_position": 190,
        "alignment": 2,
        "remove_punctuation": True,
    },
    "Word Killer (TikTok)": {
        "font_name": "Impact",
        "font_size": 38,
        "base_color": "#FF0000",
        "highlight_color": "#FF0000",
        "outline_color": "#000000",
        "outline_thickness": 3,
        "shadow_color": "#000000",
        "shadow_size": 3,
        "bold": True,
        "italic": False,
        "uppercase": True,
        "highlight_size": 45,
        "words_per_block": 1,
        "gap_limit": 0.2,
        "mode": "word_by_word",
        "underline": False,
        "strikeout": False,
        "border_style": 1,
        "vertical_position": 210,
        "alignment": 2,
        "remove_punctuation": True,
    },
    "Rapid Fire (Sprint)": {
        "font_name": "Impact",
        "font_size": 36,
        "base_color": "#FFFF00",
        "highlight_color": "#FFFF00",
        "outline_color": "#000000",
        "outline_thickness": 2,
        "shadow_color": "#000000",
        "shadow_size": 2,
        "bold": True,
        "italic": True,
        "uppercase": True,
        "highlight_size": 42,
        "words_per_block": 1,
        "gap_limit": 0.3,
        "mode": "word_by_word",
        "underline": False,
        "strikeout": False,
        "border_style": 1,
        "vertical_position": 210,
        "alignment": 2,
        "remove_punctuation": True,
    },
    "Educational Fast": {
        "font_name": "Roboto-Bold",
        "font_size": 28,
        "base_color": "#FFFFFF",
        "highlight_color": "#00BFFF",
        "outline_color": "#000000",
        "outline_thickness": 2,
        "shadow_color": "#000000",
        "shadow_size": 1,
        "bold": True,
        "italic": False,
        "uppercase": False,
        "highlight_size": 34,
        "words_per_block": 3,
        "gap_limit": 0.45,
        "mode": "highlight",
        "underline": False,
        "strikeout": False,
        "border_style": 1,
        "vertical_position": 220,
        "alignment": 2,
        "remove_punctuation": False,
    },
    "Podcast Viral (Centered)": {
        "font_name": "Arial",
        "font_size": 26,
        "base_color": "#FFFFFF",
        "highlight_color": "#00FFAA",
        "outline_color": "#000000",
        "outline_thickness": 2,
        "shadow_color": "#000000",
        "shadow_size": 1,
        "bold": True,
        "italic": False,
        "uppercase": False,
        "highlight_size": 30,
        "words_per_block": 4,
        "gap_limit": 0.55,
        "mode": "highlight",
        "underline": False,
        "strikeout": False,
        "border_style": 1,
        "vertical_position": 240,
        "alignment": 2,
        "remove_punctuation": True,
    },
    "Drama Emocional": {
        "font_name": "Arial",
        "font_size": 28,
        "base_color": "#EAEAEA",
        "highlight_color": "#FF5555",
        "outline_color": "#000000",
        "outline_thickness": 2,
        "shadow_color": "#000000",
        "shadow_size": 2,
        "bold": True,
        "italic": False,
        "uppercase": False,
        "highlight_size": 34,
        "words_per_block": 2,
        "gap_limit": 0.6,
        "mode": "highlight",
        "underline": False,
        "strikeout": False,
        "border_style": 1,
        "vertical_position": 235,
        "alignment": 2,
        "remove_punctuation": True,
    },
    "Story Subtitle (Netflix Style)": {
        "font_name": "Arial",
        "font_size": 24,
        "base_color": "#FFFFFF",
        "highlight_color": "#FFFFFF",
        "outline_color": "#000000",
        "outline_thickness": 0,
        "shadow_color": "#000000",
        "shadow_size": 1,
        "bold": True,
        "italic": False,
        "uppercase": False,
        "highlight_size": 24,
        "words_per_block": 7,
        "gap_limit": 0.7,
        "mode": "no_highlight",
        "underline": False,
        "strikeout": False,
        "border_style": 3,
        "vertical_position": 250,
        "alignment": 2,
        "remove_punctuation": False,
    },
    "Neon Cyber": {
        "font_name": "Arial",
        "font_size": 30,
        "base_color": "#FF00FF",
        "highlight_color": "#00FFFF",
        "outline_color": "#FFFFFF",
        "outline_thickness": 1,
        "shadow_color": "#000000",
        "shadow_size": 3,
        "bold": True,
        "italic": False,
        "uppercase": True,
        "highlight_size": 36,
        "words_per_block": 2,
        "gap_limit": 0.5,
        "mode": "highlight",
        "underline": True,
        "strikeout": False,
        "border_style": 1,
        "vertical_position": 205,
        "alignment": 2,
        "remove_punctuation": True,
    },
    "Retro Pixel": {
        "font_name": "Consolas",
        "font_size": 26,
        "base_color": "#00FF00",
        "highlight_color": "#00FF00",
        "outline_color": "#000000",
        "outline_thickness": 2,
        "shadow_color": "#000000",
        "shadow_size": 0,
        "bold": False,
        "italic": False,
        "uppercase": True,
        "highlight_size": 26,
        "words_per_block": 1,
        "gap_limit": 0.5,
        "mode": "word_by_word",
        "underline": False,
        "strikeout": False,
        "border_style": 3,
        "vertical_position": 215,
        "alignment": 2,
        "remove_punctuation": True,
    },
}


def generate_preview_html(
    font, size, color, highlight, outline, outline_thick, shadow, shadow_sz,
    bold, italic, upper, h_size, w_block, gap, mode, under, strike, border_s,
    vert_pos, align, remove_punc, bg_data_uri=None,
):
    font_weight = "bold" if bold else "normal"
    font_style = "italic" if italic else "normal"
    text_transform = "uppercase" if upper else "none"
    text_decorations = []
    if under:
        text_decorations.append("underline")
    if strike:
        text_decorations.append("line-through")
    text_decoration = " ".join(text_decorations) if text_decorations else "none"

    text_shadow = f"{shadow_sz}px {shadow_sz}px 0px {shadow}" if shadow_sz > 0 else "none"
    outline_css = (
        f"-webkit-text-stroke: {outline_thick}px {outline}; text-stroke: {outline_thick}px {outline};"
        if outline_thick > 0
        else ""
    )

    sample_text = "THIS IS A PREVIEW" if upper else "This is a preview"
    if mode == "highlight":
        words = sample_text.split()
        if len(words) >= 2:
            highlighted = f'<span style="color: {highlight}; font-size: {h_size}px;">{words[0]}</span> {" ".join(words[1:])}'
        else:
            highlighted = f'<span style="color: {highlight};">{sample_text}</span>'
    elif mode == "word_by_word":
        highlighted = f'<span style="color: {highlight}; font-size: {h_size}px;">{sample_text.split()[0]}</span>'
    else:
        highlighted = sample_text

    return f"""<div style="display: flex; align-items: center; justify-content: center; width: 100%; height: 200px; background: #18181b; border-radius: 8px; overflow: hidden;">
  <div style="font-family: '{font}', sans-serif; font-size: {size}px; color: {color}; font-weight: {font_weight}; font-style: {font_style}; text-transform: {text_transform}; text-decoration: {text_decoration}; text-shadow: {text_shadow}; {outline_css} text-align: center; padding: 10px;">
    {highlighted}
  </div>
</div>"""
